### ISSUE TITLE
Minimal Example in Python 

### ISSUE THREAD

**Issue by andrewcz** [joaquinr-uner/MSI_HarmDecomp#1]
Hi @joaquinr-uner I hope your well!
for a project im planning on converting some of your code to build a minimal example 
of the main algorithm in python.
Would i be able to get some direction on which files to convert.

Thank you in advance.
best wishes,
Andrew

**Comment by joaquinr-uner** [comment]
Hello Andrew,

I would recommend focusing mainly in the main three steps of the algorithm, namely, initial imputation, harmonic decomposition and harmonic interpolation. I recommend checking the ready-to-use version of this repository [here](https://github.com/joaquinr-uner/harmonic_imputation) to check how the work pipeline for this method is structured. 

Cheers and good luck with your project.

Joaquin

**Comment by andrewcz** [comment]
thank you :)
